### ISSUE TITLE
I can't find res resource

### ISSUE THREAD

**Issue by zhongjiejiang** [privet56/Scene3D2Gif#1]
Dear Sir

I can't find the res folder resource,  such as res\panorama\skybox5\, 3ds, where can I get them :)

thanks
zhongjie

**Comment by privet56** [comment]
The skybox - *.jpg resources ('skybox5' is actually a directory) aren't part of the project.
I use some demo pics, put in the subdirectory Scene3D2Gif/Scene3D2Gif/Scene3D2Gif/bin/Debug/res/panorama/skybox5/*.jpg of my built executable.
Attached are these demo pics: "res.panorama.skybox5.zip".

With these or similar pictures, the skybox should work.
[res.panorama.skybox5.zip](https://github.com/privet56/Scene3D2Gif/files/2571480/res.panorama.skybox5.zip)
